### ISSUE TITLE
64-bit Update For Healer Toolbox?

### ISSUE THREAD

**Issue by Haru-Kasugano** [Koekkruimels/tera-healer-toolbox#2]
Hey, I returned to Tera and loaded up my toolbox and got this error. Is it possible to fix it? Really enjoyed Healer Toolboxes notification system!

[11:52:51.283] [mods] ERROR: Module "Healer Toolbox" could not be applied to server connection!
[11:52:51.287] [mods] ERROR: Please contact the module's author: https://github.com/Koekkruimels/tera-healer-toolbox/issues
[11:52:51.290] Error: [dispatch] [healer toolbox] hook: Error: version 15 of message (name: "S_SPAWN_USER", code: 37833) is outdated and cannot be used anymore
    at Dispatch.createHook (E:\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (E:\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at Proxy.hook (E:\CaaliTeraProxy\bin\mod.js:280:36)
    at new healerToolbox (E:\CaaliTeraProxy\mods\Healer Toolbox\index.js:137:14)
    at new <anonymous> (E:\CaaliTeraProxy\bin\mod-legacy-wrapper.js:145:13)
    at Mod.loadNetworkInstance (E:\CaaliTeraProxy\bin\mod.js:595:31)
    at ModManager.loadNetwork (E:\CaaliTeraProxy\bin\mod-manager.js:252:20)
    at E:\CaaliTeraProxy\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (E:\CaaliTeraProxy\bin\mod-manager.js:231:25)

**Comment by TheMorgue69** [comment]
Same problem here too. Thanks for the great toolbox !

**Comment by Koekkruimels** [comment]
I haven't played Tera for a long while now, but I applied a fix that hopefully solves it, please let me know if it works now!

**Comment by TheMorgue69** [comment]
-->Wow thanks for looking into it  so promptly Even tho the gameplay ceased ! I still have this error... [12:40:17.770] [mods] ERROR: Module "Healer Toolbox" could not be applied to server connection! [12:40:17.771] [mods] ERROR: Please contact the module's author: https://github.com/Koekkruimels/tera-healer-toolbox/issues [12:40:17.772] Error: [dispatch] [healer toolbox] hook: Error: version 15 of message (name: "S_SPAWN_USER", code: 37833) is outdated and cannot be used anymore at Dispatch.createHook (C:\Games\tera-toolbox-master\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27) at Dispatch.hook (C:\Games\tera-toolbox-master\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27) at Proxy.hook (C:\Games\tera-toolbox-master\bin\mod.js:280:36) at new healerToolbox (C:\Games\tera-toolbox-master\mods\Healer Toolbox\index.js:137:14) at new <anonymous> (C:\Games\tera-toolbox-master\bin\mod-legacy-wrapper.js:145:13) at Mod.loadNetworkInstance (C:\Games\tera-toolbox-master\bin\mod.js:595:31) at ModManager.loadNetwork (C:\Games\tera-toolbox-master\bin\mod-manager.js:252:20) at C:\Games\tera-toolbox-master\bin\mod-manager.js:233:22 at Map.forEach (<anonymous>) at ModManager.loadAllNetwork (C:\Games\tera-toolbox-master\bin\mod-manager.js:231:25) [12:40:17.773] [mods] Applied module "InstantEverything" (instant-everything) to server conn -----Maybe it’s since it’s now on an EU server not NA now ?   Sent from Mail for Windows 10 From: KoekkruimelsSent: November 17, 2020 9:55 AMTo: Koekkruimels/tera-healer-toolboxCc: TheMorgue69; CommentSubject: Re: [Koekkruimels/tera-healer-toolbox] 64-bit Update For Healer Toolbox? (#2) I haven't played Tera for a long while now, but I applied a fix that hopefully solves it, please let me know if it works now!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Koekkruimels** [comment]
@TheMorgue69 Thank you, I found one missing change I just applied, Could you try again? Make sure to download this plugin again.

The problem is that I use the event `S_SPAWN_USER` of version 15 and they changed it to 16, because of some incompatibility.

Make sure your local file `manifest.json` and `constants.js` contain `S_SPAWN_USER` with the number 16.

**Comment by TheMorgue69** [comment]
Seems ok now that I downloaded pack instead of auto update THANKS a bunch !

**Comment by Mephistou** [comment]
[03:23:20.653] [update] ERROR: Unable to auto-update module Healer Toolbox:
[03:23:20.654] Failed to update the following module files:
 - constants.js
 - ERROR: https://raw.githubusercontent.com/Koekkruimels/tera-healer-toolbox/master/constants.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
   + NoPing (if you're using it) has a bug that can fuck up the download
[03:23:20.656] [update] Please go to https://github.com/Koekkruimels/tera-healer-toolbox/issues and follow the given instructions or ask for help.
[03:23:20.656] [update] Alternatively, ask here: https://discord.gg/659YbNY

this is what error i get

**Comment by Koekkruimels** [comment]
@Mephistou Updated the Manifest.json to include the correct SHA. If it still doesn't work, try to download this mod locally or create a new issue here.

**Comment by Burakkii** [comment]
![Снимок экрана 2021-08-09 100842](https://user-images.githubusercontent.com/88650560/128671671-61007de9-2996-4108-9dab-d864a2d8e78c.png)
Good day, sir! I know that u r not playin tera but this module is soo good! Could u do something about my problem?
